apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin4
  labels:
    name: phpmyadmin4
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32500
      name: http
  selector:
         app: phpmyadminlab4  
