apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deploy-lab3
spec:
  selector:
    matchLabels:
      app: mysql-deploy-lab3
  template:
    metadata:
      labels:
        app: mysql-deploy-lab3
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: cloudaccess
        ports:
        - containerPort: 3306
          name: mysql
