apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    role: webserver
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
