apiVersion: v1
kind: Pod
metadata:
  name: pma
  labels:
    role: webserver
spec:
  containers:
    - name: pma
      image: phpmyadmin/phpmyadmin
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
