apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    role: database
spec:
  containers:
    - name: db
      image: mariadb
      env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: cloudaccess
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
